Refactorizar boilerplate para que los componentes sean stateless
Liftitapp/react-native-liftit-boilerplate pull request #1
Opened 2017-06-13 14:56 UTC by qavor

Refactor test folder, removed unnecesary components

2017-06-13 15:14 UTC, johanmendezb requested changes
falta revisión de Angel

2017-06-13 15:14 UTC, johanetox commented on App/Redux/index.js
> +    github: require('./github_redux').reducer
se puede intentar los em6 import?
no estoy seguro de como sería
`import github, { reducer } from 'github_redux'`
`import github from 'github_redux/reducer'`

2017-06-13 15:14 UTC, johanetox commented on app/components/launch_panel/launch_panel.js
> +  return (
Está exportando dos veces lo mismo y el return sobra
```
const launchPanel = ({ text }) => (
  <View>
    ...
  </View>
)
export default launchPanel
```

2017-06-13 15:14 UTC, johanetox commented on app/containers/launch_container.js
> +// Actions  ====================================================================
comentario sobra

2017-06-13 15:14 UTC, johanetox commented on app/screens/launch_screen.js
> +}
```
const LaunchScreen = () => ()
export default LaunchScreen
```

2017-06-13 22:44 UTC, angelbotto requested changes

2017-06-13 22:44 UTC, angelbotto commented on App/Redux/index.js
> +    github: require('./github_redux').reducer
sip, correcto, no esta mal hacerlo con el require, pero manejemos el estandar de que todo sea con import

2017-06-13 22:44 UTC, angelbotto commented on app/components/rounded_button/rounded_button.js
> +import ExamplesRegistry from './../../services/examples_registry'
esto no me gusta nada nadita seguramente a semaphoreci y a codeclimate tampoco. 

tenemos que buscar la forma de mejorar './../../'

2017-06-13 22:44 UTC, angelbotto commented on app/containers/launch_container.js
> +// Actions  ====================================================================
como asi que comentario sobra?

2017-06-13 22:44 UTC, angelbotto commented on app/screens/launch_screen.js
> +}
pilas que la brancha es para pasar los componentes a staless y esto no es eso xD

2017-06-13 22:44 UTC, angelbotto commented on app/services/rehydration_services.js
> +  // const startup = () => store.dispatch(StartupActions.startup())
eliminar esto si no se usa o dejar un TODO: indicando pprque no se borra

2017-06-13 22:44 UTC, angelbotto commented on tests/components/rounded_button_test.js
> +import RoundedButton from '../../app/components/rounded_button'
../../

2017-06-14 16:34 UTC, johanmendezb requested changes

2017-06-14 16:34 UTC, johanmendezb commented on app/containers/root_container.js
> +import styles from 'app/containers/styles/root_container_styles'
no está muy larga esta ruta?

2017-06-14 16:34 UTC, johanetox commented on app/containers/root_container.js
> +  // startup: () => dispatch(StartupActions.startup())
quitar comentarios

2017-06-14 16:34 UTC, johanetox commented on app/package.json
> +}
por qué hay dos package.json?

2017-06-14 16:34 UTC, johanetox commented on app/containers/root_container.js
> +import styles from 'app/containers/styles/root_container_styles'
el root del path debería ser desde `app/` si pero sin llamarlo 
`import styles from 'containers/styles/root_container_styles'`

2017-06-14 16:34 UTC, johanetox commented on App/Config/index.js
> +import DebugConfig from 'app/config/debug_config'
quitar los dos `console.log` en `app/services/immutable_persistence_transform.js`

2017-06-14 17:21 UTC, angelbotto requested changes

2017-06-14 17:21 UTC, angelbotto commented on app/containers/root_container.js
> +import styles from 'app/containers/styles/root_container_styles'
creo que esto ya es tema de react-native ya que no gestionamos con webpack :P

2017-06-14 17:21 UTC, angelbotto commented on app/package.json
> +}
este es para poder definir en el root y no llamar ../../ si no directamente . app/

2017-06-14 21:27 UTC, johanmendezb approved these changes

2017-06-14 21:44 UTC, angelbotto approved these changes

2017-06-14 21:59 UTC, merged