First version on README.md done
Liftitapp/react-native-liftit-boilerplate pull request #12
Opened 2017-07-06 20:50 UTC by davidquinto

2017-07-06 20:59 UTC, angelbotto approved these changes
esta nice nice, solo creo que podriamos mejorar el tema de bajar el repo y cambiar el nombre del app que te dejo en los comentarios de resto todo genial congrats!

2017-07-06 20:59 UTC, angelbotto commented on README.md
> +**Step 1:** `git clone https://github.com/Liftitapp/react-native-liftit-boilerplate.git`
esto podemos mejorarlo indicando q agreguen el nombre del proyecto

```git clone https://github.com/Liftitapp/react-native-liftit-boilerplate.git ProjectName```

2017-07-06 20:59 UTC, angelbotto commented on README.md
> +* [ReactNativeConfig](https://github.com/luggit/react-native-config) - Environment vars for React components and Android (*.xml, *.gradle, *.java) files. - [+ info](#react-native-config)
😎

2017-07-06 20:59 UTC, angelbotto commented on README.md
> +This module read the `.env` file from the root folder, and stores their variables on the `process.env` object.
vamos agregando aca porfa las variables de entorno que tenemos y un ejemplo

GITHUB_TOKEN='***********'

algo asi para que sea claro cuales deben tener precentes en su .env

2017-07-06 20:59 UTC, angelbotto commented on README.md
> +The minimum vars required by this project are:
👌🏻

2017-07-07 16:12 UTC, johanmendezb requested changes

2017-07-07 16:12 UTC, johanetox commented on README.md
> +      * `react-native run-android`
podemos poner también sobre la configuración de los paquetes de android, y sobre correr `npm run start` antes de `react-native run-android`? lo menciono porque si uno corre el anterior comando usualmente se ejecuta desde la terminal por defecto del sistema, qué opinan? @angelbotto @davidquinto

2017-07-07 16:12 UTC, johanetox commented on README.md
> +This module read the `.env` file from the root folder, and stores their variables on the `process.env` object.
exacto, hagamos un archivo de ejemplo, es más este paso debería estar antes de corre el proyecto, sin el `.env` no va a correr la vaina

2017-07-07 16:12 UTC, johanetox commented on README.md
> +#  ReactNativeLiftitBoilerplate [![js-standard-style](https://img.shields.io/badge/code%20style-standard-brightgreen.svg?style=flat)](http://standardjs.com/) [![Build Status](https://semaphoreci.com/
no me gusta el título ReactNativeLiftitBoilerplate, prropongamos otro, tal vez React-Native redux sagas Boilerplate, o no sé propongan

2017-07-07 16:12 UTC, johanetox commented on README.md
> +* [ReactNativeConfig](https://github.com/luggit/react-native-config) - Environment vars for React components and Android (*.xml, *.gradle, *.java) files. - [+ info](#react-native-config)
@davidquinto nos falta mencionar, sagas, redux, apisauce, y no sé revise bien el package XD

2017-07-07 18:41 UTC, angelbotto requested changes

2017-07-07 18:41 UTC, angelbotto commented on README.md
> +#  ReactNativeLiftitBoilerplate [![js-standard-style](https://img.shields.io/badge/code%20style-standard-brightgreen.svg?style=flat)](http://standardjs.com/) [![Build Status](https://semaphoreci.com/
el nombre me gusta React Native Liftit Boilerplate, le ponemos los tags que digan que tecnologia tiene

2017-07-07 18:41 UTC, angelbotto commented on README.md
> +      * `react-native run-android`
yes!

2017-07-10 20:28 UTC, angelbotto approved these changes

2017-07-10 20:29 UTC, johanmendezb approved these changes

2017-07-10 20:29 UTC, merged