Agregar dotenv para las variables de entorno para gradle y para js
Liftitapp/react-native-liftit-boilerplate pull request #3
Opened 2017-06-15 00:10 UTC by qavor

2017-06-15 00:11 UTC, qavor commented on .env
> +APP_VERSION_NAME=0.0.1
Perdón por esto XD

2017-06-15 00:12 UTC, angelbotto commented on .env
> +APP_VERSION_NAME=0.0.1
jajajajajajajajajajajajaja

2017-06-15 00:19 UTC, angelbotto requested changes

2017-06-15 00:19 UTC, angelbotto commented on .env
> +APP_VERSION_NAME=0.0.1
desaparecer

2017-06-20 15:25 UTC, johanmendezb approved these changes

2017-06-20 20:28 UTC, angelbotto approved these changes

2017-06-20 20:41 UTC, merged