Agregar @flow a todos los componentes, reductores, sagas y contenedores
Liftitapp/react-native-liftit-boilerplate pull request #8
Opened 2017-06-28 21:31 UTC by davidquinto

2017-06-28 22:38 UTC, johanmendezb requested changes

2017-06-28 22:38 UTC, johanetox commented on app/components/launch_panel/launch_panel.js
> +        <RoundedButton text={props.text} onPress={alertMessage} />
si en el import hace esto:
`const launchPanel = ({ text }: _type: ) => (`
abajo no necesitaría hacer `props.text` sino llamar `text directamente`

2017-06-28 22:38 UTC, johanetox commented on app/components/rounded_button/rounded_button.js
> +    <Text style={styles.buttonText}>{props.text.toUpperCase()}</Text>
importar los props con em6 para tener el código más limpio, ejemplo en el comentario anterior

2017-06-29 16:48 UTC, johanmendezb approved these changes

2017-06-29 16:48 UTC, johanetox commented on app/themes/colors.js
> +  backgroundColor: '#FFF',
cuál es la diferencia de `backgroundColor`y `background`?

2017-06-29 22:49 UTC, angelbotto requested changes
hagamos estos cambios porfa!

2017-06-29 22:49 UTC, angelbotto commented on app/components/launch_panel/launch_panel.js
> +const launchPanel = ({ text }: _type) => (
porque _type

2017-06-29 22:49 UTC, angelbotto commented on .eslintrc
> +    "Generator": true
q jesto chico

2017-06-29 22:49 UTC, angelbotto commented on .eslintrc
> +    "Generator": true
ya entendi! :)

2017-06-29 22:49 UTC, angelbotto commented on app/components/launch_panel/launch_panel.js
> +  text: string
thanks!

2017-06-29 22:49 UTC, angelbotto commented on app/services/api.js
> +const create = (baseURL: string = 'https://api.github.com/') => {
esto deberia estar en las variables de entorno en el .env y en semaphore 😀

2017-06-29 22:49 UTC, angelbotto commented on app/themes/metrics.js
> +const CalcScreenWidth = (_width: number = width, _height: number = height): number => _width < _height ? _width : _height
chao variables con _ 😅

2017-06-30 16:15 UTC, angelbotto approved these changes

2017-06-30 16:16 UTC, merged